version: "2.1"

services:

  activemq:
    image: webcenter/activemq:5.14.3
    ports:
      - "1883:1883"   # mqtt
      - "5672:5672"   # amqp
      - "8161:8161"   # ui
      - "61613:61613" # stomp
      - "61614:61614" # ws
      - "61616:61616" # jms
    networks: [backing-services]
    volumes:
      - "activemq-data:/opt/activemq/conf"
      - "activemq-data:/data/activemq"
      - "activemq-data:/var/log/activemq"
    environment:
      ACTIVEMQ_MIN_MEMORY: 512
      ACTIVEMQ_MAX_MEMORY: 2048
      ACTIVEMQ_ENABLED_SCHEDULER: "true"
      ACTIVEMQ_REMOVE_DEFAULT_ACCOUNT: "true"
      ACTIVEMQ_ADMIN_LOGIN: admin
      ACTIVEMQ_ADMIN_PASSWORD: password

  postgres:
    image: healthcheck/postgres:alpine
    ports: ["5432:5432"]
    networks: [backing-services]
    volumes: ["postgres-data:/var/lib/postgresql/data"]
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

volumes:
  activemq-data: {}
  postgres-data: {}

networks:
  backing-services:
    driver: bridge
