version: "2.1"
services:
  mq:
    container_name: activemq
    image: webcenter/activemq:5.14.3
    ports: ["8161:8161", "61613:61613", "61616:61616"]
    networks: [backing-services]
    volumes: ["mq-data:/data/activemq", "mq-data:/var/log/activemq"]
    environment:
      ACTIVEMQ_REMOVE_DEFAULT_ACCOUNT: "true"
      ACTIVEMQ_ADMIN_LOGIN: admin
      ACTIVEMQ_ADMIN_PASSWORD: password
      ACTIVEMQ_WRITE_LOGIN: write
      ACTIVEMQ_WRITE_PASSWORD: password
      ACTIVEMQ_READ_LOGIN: read
      ACTIVEMQ_READ_PASSWORD: password
      ACTIVEMQ_JMX_LOGIN: jmx
      ACTIVEMQ_JMX_PASSWORD: password
      ACTIVEMQ_STATIC_TOPICS: static-topic-1;static-topic-2
      ACTIVEMQ_STATIC_QUEUES: static-queue-1;static-queue-2
      ACTIVEMQ_ENABLED_SCHEDULER: "true"
      ACTIVEMQ_MIN_MEMORY: 512
      ACTIVEMQ_MAX_MEMORY: 2048
  db:
    container_name: postgres
    image: healthcheck/postgres:alpine
    ports: ["5432:5432"]
    networks: [backing-services]
    volumes: ["db-data:/var/lib/postgresql/data"]
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
volumes:
  mq-data: {}
  db-data: {}
networks:
  backing-services:
    driver: bridge
